name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build,Test,and Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Restore .NET dependencies
      run: dotnet restore
      working-directory: api/Basic3TierAPI

    - name: Build .NET project
      run: dotnet build --no-restore --configuration Release
      working-directory: api/Basic3TierAPI

    - name: Run .NET tests
      run: dotnet test --no-build --configuration Release --verbosity normal
      working-directory: api/Basic3TierAPI

    - name: Install frontend dependencies
      run: npm install
      working-directory: ui
      
    - name: Build frontend
      run: npm run build
      working-directory: ui
      
    - name: SonarQube Scan
      run: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
              
        
